routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AboutusController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\ContactusController;
use App\Http\Controllers\LogopageController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OrderController;




use Illuminate\Support\Facades\Auth;







/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can 6 web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/@/{name}', function () {
    return view('welcome');
});

Route::get('/@/{product}/{slug}', function () {
    return view('welcome');
});


Route::get('/logout', [LoginController::class, 'logout']);

// Route::group(['as'=>'admin.', 'prefix' => 'admin', 'namespace'=>'', 'middleware' => ['auth','admin']], function(){



//     // Route::get('category', [CategoryController::class, 'index'])->name('category/index');
//     // Route::get('category/create', [CategoryController::class, 'create'])->name('category/index');
//     // Route::get('category/{id}/edit', [CategoryController::class, 'edit'])->name('category/index');
//     // Route::post('category', [CategoryController::class, 'store'])->name('category/index');
//     // Route::delete('category/{id}', [CategoryController::class, 'index'])->name('category/index');


// });
Route::group(['as'=>'admin.', 'prefix' => 'admin', 'namespace'=>'', 'middleware' => ['auth','admin']], function(){

    Route::resource('products', ProductController::class);
    Route::resource('location', LocationController::class);
    Route::resource('country', CountryController::class);
    Route::resource('aboutus', AboutusController::class);
    Route::resource('slider', SliderController::class);
    Route::resource('contactus', ContactusController::class);
    Route::resource('logopage', logopageController::class);
    Route::resource('users', UserController::class);
    Route::resource('category', CategoryController::class);
    Route::resource('order', OrderController::class);
    Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'index'])->name('profile');
    Route::post('profile/{user}', [App\Http\Controllers\ProfileController::class, 'update'])->name('profile.update');
    Route::get('change-password', [App\Http\Controllers\HomeController::class, 'changePassword'])->name('change-password');
    Route::post('change-password', [App\Http\Controllers\HomeController::class, 'updatePassword'])->name('update-password');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');




});




Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Country.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    use HasFactory;
    
}

app/Http/Controllers/Api/CountryController.php
<?php
// 
namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Services\CountryService;
use Illuminate\Http\Request;



class CountryController extends Controller
{
    public $service;
    public function __construct(){
        $this->service = new CountryService();
    }

    function index(Request $request){
        
        $country = $this->service->all();
// doesn't return view
        return response()->json(['status'=>'success','msg'=>'','data'=> $country]);
    }
}

app/Http/Controllers/CountryController.php
<?php
namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Country;
use App\Http\Services\CountryService;

class CountryController extends Controller
{
    public $service;
    public function __construct(){

        //$this->middleware('auth');

        //$this->middleware('role:ROLE_ADMIN');

        // calling service
        $this->service = new CountryService();
    }

    function index(Request $request){
//      all db data are stored       service/fuc name = all
        $country = $this->service->all();

        return view('country.index', compact('country'));
    }
    public function create()
    {
        return view('country.create');

    }
    public function store(Request $request){
        $id = $request->input('id');
        if(empty($id)){
            $addcountry = $this->service->insert($request);
        }
        else{
            $addcountry = $this->service->update($request,$id);
        }
        
        return redirect()->route('admin.country.index');  
    }
    public function edit($id)
    {
        $country =  Country::find($id);

        return view('country.edit',compact('id', 'country'));
    }
    public function destroy($id){
        $this->service->delete($id);
        return redirect()->route('admin.country.index');        
    }
}

resources/views/country/create.blade.php
@extends('adminlte::page')
@section('content')
<div style="background-color:white; margin:0px;  height:100vh; " >
<h1 style="text-align: center;color:#ed1874;font-weight:bold; padding-top:20px;"> Add Country </h1>

<form action="{{ route('admin.country.store') }}" method="POST" enctype="multipart/form-data">
    @csrf

    <table class="c-form" style="color:#ed1874; font-size:24px; font-weight:bold; margin-top:30px; margin-left:25px;   ">
        <tr>
            <td>Country Name:</td>
            <td ><input type="text" name="country_name" style="border:none; background-color:#fbe9f5; outline:none; border-radius:8px; margin:10px;" required></td>
        </tr>

    </table>
    <button type ="submit" style="background-color: rgb(15, 174, 15); margin-left:25px; color:white; height:40px; width:60px; border-radius:8px; border:none; margin-top:10px; font-weight:bold;" > Create</button>
</form>
</div>
@endsection
@section('css')
    <link rel="stylesheet" href="{{ url('/css/createStyle.css') }}">

@stop

resources/views/country/edit.blade.php
@extends('adminlte::page')
@section('content')
<div style="background-color:white; margin:0px;  height:100vh; " >

    <h1 style="text-align: center;color:#ed1874;font-weight:bold; padding-top:20px;"> Edit Country </h1>

    <form action="{{ route('admin.country.store', [$country->id]) }}" method="POST" enctype="multipart/form-data">
        @csrf
        <input type="hidden" name='id' value="{{$id}}"/>
        <table style="color:#ed1874; font-size:24px; font-weight:bold; margin-top:30px; margin-left:25px;   ">
            {{-- <div class="input-box">
            <input type="hidden" name="id" value="{{$category['id']}}"
                style="padding: 10px; margin-top: 42px; margin-left: -68px;" />
        </div> --}}
            <tr>
                <td>Country Name:</td>
                <td><input type="text" name="country_name" value="{{ $country['country_name'] }}" style="border:none; background-color:#fea4c5; outline:none; border-radius:8px; margin:10px; color:#ed1874; padding-left:15px;"></td>
            </tr>
            
           

            
          
          

        </table>
        <button type="submit" value="" style="background-color: rgb(15, 174, 15); margin-left:25px; color:white; height:40px; width:65px; border-radius:8px; border:none; margin-top:10px; font-weight:bold;"> Update</button>
        {{-- </form> --}}
</div>
    @endsection
    @section('css')
    <link rel="stylesheet" href="{{ url('/css/editStyle.css') }}">

@stop

resources/views/country/index.blade.php
@extends('adminlte::page')

@section('content')

    @php
   
        $heads = ['S.N', 'Country_Name',  'Actions'];
     
    @endphp
    @if(session()->get('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}
    </div>
    @endif
    @if(session()->get('danger'))
    <div class="alert alert-danger">
        {{ session()->get('danger') }}
    </div>
    @endif

    <x-adminlte-datatable id="table1" :heads="$heads" theme="danger">
        <!-- Displaying table on our dashboard (html page) -->
        {{-- <a class="btn btn-success my-3 " style="margin-right:20px"  href="{{ route('admin.users.create') }}"> Add Organization</a>
        <a class="btn btn-success my-3 " style="margin-right:20px"  href="{{ route('admin.staff_create') }}"> Add Organization Users</a> --}}




        <h1 style="text-align: center;color:#ed1874;font-weight:bold; margin-top:25px;">Country List</h1>
        <a href="{{route('admin.country.create')}}"   class="btn btn-xl btn-default mx-1 shadow bg-success my-3" title="Create">Add Country</a>
        @foreach ($country as $countrylist)
            <tr style="background-color:#ed1874; color:white; font-size:22px;">
                <td>{{ $loop->iteration }}</td>
                <td>{{ $countrylist->country_name}}</td>



                <td class="d-flex">
                    <span class="action-btn">

                        <a style="font-size:16px " href="{{ route('admin.country.edit', [$countrylist->id]) }}"
                            class="btn btn-xs btn-default text-primary mx-1 shadow" title="Edit">
                            <i class="fa fa-lg fa-fw fa-pen"></i> </a>
                    </span>



                    <form action="{{ route('admin.country.destroy', [$countrylist->id]) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button style="font-size:16px" type="submit"
                            class="btn btn-xs btn-default text-danger mx-1 shadow" onclick="return confirm('Are you sure you want to delete this item?')"> <i class="fa fa-lg fa-fw fa-trash"></i>
                        </button>
                    </form>


                </td>



            </tr>
        @endforeach





    </x-adminlte-datatable>
    @endsection
    @section('css')
    <link rel="stylesheet" href="{{ url('/css/style.css') }}">

@stop