routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AboutusController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\ContactusController;
use App\Http\Controllers\LogopageController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OrderController;




use Illuminate\Support\Facades\Auth;







/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can 6 web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/@/{name}', function () {
    return view('welcome');
});

Route::get('/@/{product}/{slug}', function () {
    return view('welcome');
});


Route::get('/logout', [LoginController::class, 'logout']);

// Route::group(['as'=>'admin.', 'prefix' => 'admin', 'namespace'=>'', 'middleware' => ['auth','admin']], function(){



//     // Route::get('category', [CategoryController::class, 'index'])->name('category/index');
//     // Route::get('category/create', [CategoryController::class, 'create'])->name('category/index');
//     // Route::get('category/{id}/edit', [CategoryController::class, 'edit'])->name('category/index');
//     // Route::post('category', [CategoryController::class, 'store'])->name('category/index');
//     // Route::delete('category/{id}', [CategoryController::class, 'index'])->name('category/index');


// });
Route::group(['as'=>'admin.', 'prefix' => 'admin', 'namespace'=>'', 'middleware' => ['auth','admin']], function(){

    Route::resource('products', ProductController::class);
    Route::resource('location', LocationController::class);
    Route::resource('country', CountryController::class);
    Route::resource('aboutus', AboutusController::class);
    Route::resource('slider', SliderController::class);
    Route::resource('contactus', ContactusController::class);
    Route::resource('logopage', logopageController::class);
    Route::resource('users', UserController::class);
    Route::resource('category', CategoryController::class);
    Route::resource('order', OrderController::class);
    Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'index'])->name('profile');
    Route::post('profile/{user}', [App\Http\Controllers\ProfileController::class, 'update'])->name('profile.update');
    Route::get('change-password', [App\Http\Controllers\HomeController::class, 'changePassword'])->name('change-password');
    Route::post('change-password', [App\Http\Controllers\HomeController::class, 'updatePassword'])->name('update-password');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');




});




Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Category extends Model
{
    use HasFactory;
// used in index.blade
    public function categories()
    {
        // to display name insted  of id
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }

    public function products(): BelongsToMany
    {
        return $this->belongsToMany(Product::class);
    }
}

app/Http/Controllers/Api/CategoryController.php
<?php
// 
namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Services\CategoryService;
use App\Models\CategoryProduct;
use App\Models\Product;

class CategoryController extends Controller
{
    public $service;
    public function __construct(){
        $this->service = new CategoryService();
    }

    function index(Request $request){
        
        $category = $this->service->all();
// doesn't return view
        return response()->json(['status'=>'success','msg'=>'','data'=> $category]);
    }


    public function category_detail($id){
        $category = $this->service->category_detail($id);
     
        return response()->json(['status'=>'success','msg'=>'','data'=> $category]);

    }
}

app/Http/Controllers/CategoryController.php
<?php
namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\User;
use App\Http\Services\CategoryService;

class CategoryController extends Controller
{
    public $service;
    public function __construct(){

        //$this->middleware('auth');

        //$this->middleware('role:ROLE_ADMIN');

        // calling service
        $this->service = new CategoryService();
    }

    function index(Request $request){
        $category = $this->service->all();

        return view('category.index', compact('category'));
    }
    public function create()
    {

        $category = $this->service->all();


        $categories = Category::pluck('name', 'id');

        return view('category.create', compact('category','categories'));

    }
    public function store(Request $request){
        $id = $request->input('id');
        if(empty($id)){
            $addcategory = $this->service->insert($request);
        }
        else{
            $addcategory = $this->service->update($request,$id);
        }

        return redirect()->route('admin.category.index');
    }
    public function edit($id)
    {
        $category =  Category::find($id);
        $categories = Category::where('id', '!=', $id)->pluck('name', 'id');

        return view('category.edit',compact('id', 'category', 'categories'));
    }
    public function destroy($id){
        $this->service->delete($id);
        return redirect()->route('admin.category.index');
    }
}

resources/views/category/create.blade.php
@extends('adminlte::page')
@section('content')
    <div class="c-container">
        <h1 class="heading"> Add Categories </h1>

        <form action="{{ route('admin.category.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <table class="c-form">
                <tr>
                    <td>Category Name:</td>
                    <td><input type="text" name="name" class="input" required>
                    </td>
                </tr>

                <tr>
                    <td>Category Slug:</td>
                    <td><input type="text" name="slug" class="input" required>
                    </td>
                </tr>

                <tr>
                    <td>Parent Category:</td>
                    <td>
                        <select class="select" name="parent_id" id="category"  >
                            <option value="">Select</option>
                            <?php

                     // create func variable = $categories
                    foreach ($categories as $category_id => $category_name) {
                    ?>
                            <option value="{{ $category_id }}"> <?php echo $category_name; ?></option>
                            <?php } ?>
                        </select>



                    </td>
                </tr>
                <tr>
                    <td>Upload Image:</td>
                    <td><input class="img" type="file" name="image">
                    </td>

                </tr>


            </table>
            <button type="submit" class="button">
                Create</button>
        </form>
    </div>
@endsection
@section('css')
    <link rel="stylesheet" href="{{ url('/css/createStyle.css') }}">

@stop

resources/views/category/edit.blade.php
@extends('adminlte::page')
@section('content')
<div class= "container"  >

    <h1 class= "head" > Edit Categories </h1>

    <form action="{{ route('admin.category.store', [$category->id]) }}" method="POST" enctype="multipart/form-data">
        @csrf
        <input type="hidden" name="id" value="{{$id}}"/>

        <table class="e-table" >
            {{-- <div class="input-box">
            <input type="hidden" name="id" value="{{$category['id']}}"
                style="padding: 10px; margin-top: 42px; margin-left: -68px;" />
        </div> --}}
            <tr>
                <td>Category Name:</td>
                <td><input class="e-input" type="text" name="name" value="{{ $category['name'] }}" ></td>
            </tr>

            <tr>
                <td>Category Slug:</td>
                <td><input class="e-input" type="text" name="slug" value="{{ $category['slug'] }}" ></td>
            </tr>

            <tr>
                <td>Parent Category:</td>
                <td>
                    <select class="e-input" name="parent_id" id="category" >
                        <option value=0>Select</option>
                        <?php
                    foreach ($categories as $category_id => $category_name) {
                    ?>
                        <option value="<?php echo $category_id?>" @if($category['parent_id']==$category_id)
                            {{'selected=selected'}} @endif> <?php echo $category_name; ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td>Upload Image:</td>

                <td><input class="file-upload-input" type="file" name ="image"  ></td>
            </tr>
            <tr>
                <td></td>
                <td><img src="{{ url("images/". $category->image) }}" style="height:60px;width:60px" alt="logo"></td>

            </tr>


        </table>
        <button type="submit" value="" class="e-button"> Update</button>
        {{-- </form> --}}
</div>
    @endsection
    @section('css')
    <link rel="stylesheet" href="{{ url('/css/editStyle.css') }}">

@stop

resources/views/category/index.blade.php
@extends('adminlte::page')

@section('content')

    @php

        $heads = ['S.N', 'Name', 'Slug', 'Parent_id', 'Image', ['label' => 'Actions ', 'no-export' => true, 'width' => 15]];

    @endphp

    {{-- for alert display while deleting --}}
    @if(session()->get('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}
    </div>
    @endif
    @if(session()->get('danger'))
    <div class="alert alert-danger">
        {{ session()->get('danger') }}
    </div>
    @endif

    {{-- Minimal example / fill data using the component slot --}}
    <div class="main-container" >

    <x-adminlte-datatable id="table1" :heads="$heads" theme="danger">
        <!-- Displaying table on our dashboard (html page) -->
        {{-- <a class="btn btn-success my-3 " style="margin-right:20px"  href="{{ route('admin.users.create') }}"> Add Organization</a>
        <a class="btn btn-success my-3 " style="margin-right:20px"  href="{{ route('admin.staff_create') }}"> Add Organization Users</a> --}}




        <h1 class="main-heading" >Category List</h1>
                                {{-- category/createBlade --}}
        <a href="{{route('admin.category.create')}}" class="btn btn-xl btn-default mx-1 shadow bg-success my-3" title="Create">Add Category</a>

            {{-- compact name        storing category data in categorylist --}}
        @foreach ($category as $categorylist)
            <tr class="main-row">
                {{-- to display serial number --}}
                <td>{{ $loop->iteration }}</td>
                <td>{{ $categorylist->name }}</td>
                <td>{{ $categorylist->slug }}</td>
                                    {{-- model ko function name = categories--}}
                <td>{{ ($categorylist->categories != null) ? $categorylist->categories->name:'' }}</td>
                <td><img src="{{ url("images/". $categorylist->image) }}" style="height:50px;width:50px" alt="logo"></td>


                <td class="d-flex">
                    <span class="action-btn">

                        <a style="font-size:16px; margin-top:10px; margin-bottom:15px; " href="{{ route('admin.category.edit', [$categorylist->id]) }}"
                            class="btn btn-xs btn-default text-primary mx-1 shadow" title="Edit">
                            <i class="fa fa-lg fa-fw fa-pen"></i> </a>
                    </span>



                    <form action="{{ route('admin.category.destroy', [$categorylist->id]) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button style="font-size:16px; margin-top:10px; margin-bottom:15px; " type="submit"
                            class="btn btn-xs btn-default text-danger mx-1 shadow" onclick="return confirm('Are you sure you want to delete this item?')"> <i class="fa fa-lg fa-fw fa-trash"></i>
                        </button>
                    </form>


                </td>



            </tr>
        @endforeach





    </x-adminlte-datatable>
</div>

@endsection
@section('css')
    <link rel="stylesheet" href="{{ url('/css/style.css') }}">

@stop