routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AboutusController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\ContactusController;
use App\Http\Controllers\LogopageController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OrderController;




use Illuminate\Support\Facades\Auth;







/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can 6 web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/@/{name}', function () {
    return view('welcome');
});

Route::get('/@/{product}/{slug}', function () {
    return view('welcome');
});


Route::get('/logout', [LoginController::class, 'logout']);

// Route::group(['as'=>'admin.', 'prefix' => 'admin', 'namespace'=>'', 'middleware' => ['auth','admin']], function(){



//     // Route::get('category', [CategoryController::class, 'index'])->name('category/index');
//     // Route::get('category/create', [CategoryController::class, 'create'])->name('category/index');
//     // Route::get('category/{id}/edit', [CategoryController::class, 'edit'])->name('category/index');
//     // Route::post('category', [CategoryController::class, 'store'])->name('category/index');
//     // Route::delete('category/{id}', [CategoryController::class, 'index'])->name('category/index');


// });
Route::group(['as'=>'admin.', 'prefix' => 'admin', 'namespace'=>'', 'middleware' => ['auth','admin']], function(){

    Route::resource('products', ProductController::class);
    Route::resource('location', LocationController::class);
    Route::resource('country', CountryController::class);
    Route::resource('aboutus', AboutusController::class);
    Route::resource('slider', SliderController::class);
    Route::resource('contactus', ContactusController::class);
    Route::resource('logopage', logopageController::class);
    Route::resource('users', UserController::class);
    Route::resource('category', CategoryController::class);
    Route::resource('order', OrderController::class);
    Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'index'])->name('profile');
    Route::post('profile/{user}', [App\Http\Controllers\ProfileController::class, 'update'])->name('profile.update');
    Route::get('change-password', [App\Http\Controllers\HomeController::class, 'changePassword'])->name('change-password');
    Route::post('change-password', [App\Http\Controllers\HomeController::class, 'updatePassword'])->name('update-password');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');




});




Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Product extends Model
{
    use HasFactory;

    public function categories(): BelongsToMany
    {
        return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/Api/ProductController.php
<?php
//
namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Services\ProductService;
use App\Models\Product;
use App\Models\CategoryProduct;

class ProductController extends Controller
{
    public $service;
    public function __construct(){
        $this->service = new ProductService();
    }

    function index(Request $request){

        $products = $this->service->all();
// doesn't return view
        return response()->json(['status'=>'success', 'msg'=>'', 'data' => $products]);
    }

    function show($id){
        $product = Product::find($id);
        return response()->json(['status'=>'success', 'msg'=>'', 'data' => $product]);


    }

    function product_detail($slug){
        $product = Product::where('slug', $slug)->first();
        return response()->json(['status'=>'success', 'msg'=>'', 'data' => $product]);


    }
    function featured_product(Request $request){
        $products = $this->service->featured_product();
// doesn't return view
        return response()->json(['status'=>'success', 'msg'=>'', 'data' => $products]);
    }


  


}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Http\Services\ProductService;

class ProductController extends Controller
{
    public $service;
    public function __construct(){

       $this->service = new ProductService();
    }
    function index(Request $request){
        $product = $this->service->all();

        return view('products.index', compact('product'));
    }
    public function create()
    {
        $categories = Category::All();
        return view('products.create',compact('categories'));
    }
    public function store(Request $request){

        $id = $request->input('id');

        if(empty($id)){

            $addproduct = $this->service->insert($request);
        }
        else{
            $addproduct = $this->service->update($request,$id);
        }

        return redirect()->route('admin.products.index');
    }
    public function edit($id)
    {
        $categories = Category::All();
        $product =  Product::find($id);
        // dd($product);
        // die();
        $selected_categories = $product->categories->pluck('id')->toArray();

        return view('products.edit',compact('product', 'categories', 'selected_categories'));
    }
    public function destroy($id){
        $this->service->delete($id);
        return redirect()->route('admin.products.index');
    }
}

resources/views/products/create.blade.php
@extends('adminlte::page')
@section('content')
    <div class="c-container">

        <div class="p-div">
            <div class="p-left">
            <h1  class="heading">Add Products </h1>


            <form action="{{ route('admin.products.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <table class="c-form">

                    <tr>
                        <td>Name:</td>
                        <td><input type="text" name="name" class="input" required> </td>
                    </tr>
                    <tr>
                        <td>Slug:</td>
                        <td><input type="text" name="slug" class="input" required></td>
                    </tr>
                    <tr>
                        <td>Detail:</td>
                        <td>
                            <textarea class="input" name="detail" cols="50" rows="4" required></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td>Price:</td>
                        <td><input type="text" class="input" name="price" placeholder="Rs." required></td>
                    </tr>
                    <tr>
                        <td>Weight:</td>
                        <td><input type="text" class="input" name="weight" required></td>
                    </tr>
                    <tr><td></td>
                        <td>Do you want to fetured this iteam?</td>

                    </tr>

                    <tr>
                        <td></td>
                        <td>
                            <input type="checkbox" name="featured" ></td>

                    <tr>
                        <td>Image:</td>
                        <td><input type="file" name="image"></td>
                    </tr>

                </table>
                <button type="submit" class="button"> Submit</button>
            </div>
                <div class="p-right">
                    <div class="c-form1">
                        <h3 class="heading">Category</h3>
                        @foreach ($categories as $category)
                            <input type="checkbox"  id={{ $category->name }} name="category[]"
                                value={{ $category->id }}>
                            <label>{{ $category->name }}</label><br>
                        @endforeach



                    </div>
                </div>

            </div>

        </form>
    </div>
@endsection
@section('css')
    <link rel="stylesheet" href="{{ url('/css/createStyle.css') }}">

@stop

resources/views/products/edit.blade.php
@extends('adminlte::page')
@section('content')
<div class="c-container">

    <div class="p-div">
        <div class="p-left">
    <h1 class= "heading">Edit Product Form </h1>

    <form action="{{ route('admin.products.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <input type="hidden" name="id" value="{{$product->id}}" />
        <table class="c-form">

            <tr>
                <td>Name</td>
                <td><input type="text" class="e-input" name="name" value="{{ $product->name }}"></td>
            </tr>
            <tr>
                <td>Slug</td>
                <td><input type="text" class="e-input" name="slug" value="{{ $product->slug }}"></td>
            </tr>
            <tr>
                <td>Detail</td>
                <td><textarea name="detail" class="e-input" cols="50" rows="4">{{ $product->detail }}</textarea></td>
            </tr>
            <tr>
                <td>Price</td>
                <td><input type="text" class="e-input" name="price" value="{{ $product->price }}"></td>
            </tr>
            <tr>
                <td>Weight</td>
                <td><input type="text" class="e-input" name="weight" value="{{ $product->weight }}"></td>
            </tr>
            <tr><td></td>
                <td>Do you want to fetured this iteam?</td>

            </tr>

            <tr>
                <td></td>
                <td>
                    <input type="checkbox"  name="featured" value ={{$product->featured}}  {{$product->featured ==1? 'checked' : '0'}}/>

            <tr>
            <tr>
                <td>Image</td>
                <td><input type="file" name="image"></td>

                {{-- <img src="{{ url('images/' . $products->image) }}" style="height:60px;width:60px" alt="logo"> --}}

            </tr>
            <tr>
                <td></td>
                <td><img src="{{ url('images/' . $product->image) }}" style="height:60px;width:60px" alt="logo"></td>

            </tr>

        </table>
        <button type="submit" class="button"> Update</button>
    </div>
        <div class="p-right">
            <div class="c-form1">
                <h3 class= "heading">Category</h3>
                @foreach ($categories as $category)
                    <input type="checkbox"  id={{ $category->name }} name="category[]"
                        value={{ $category->id }} @if(in_array($category->id, $selected_categories)) checked="checked" @endif>
                    <label>{{ $category->name }}</label><br>
                @endforeach



            </div>
        </div>



    </form>
@endsection
@section('css')
    <link rel="stylesheet" href="{{ url('/css/createStyle.css') }}">

@stop

resources/views/products/index.blade.php
@extends('adminlte::page')

@section('content')

    @php
    $heads = [
        'S.N.',
        'Name',
        'image',
        'Slug',
        'Categories',
        'Price',
        'Weight',
        ['label' => 'Actions', 'no-export' => true, 'width' => 15],
    ];


    @endphp

     {{-- for alert display while deleting --}}
 @if(session()->get('success'))
 <div class="alert alert-success">
     {{ session()->get('success') }}
 </div>
 @endif
 @if(session()->get('danger'))
 <div class="alert alert-danger">
     {{ session()->get('danger') }}
 </div>
 @endif
    {{-- Minimal example / fill data using the component slot --}}


<x-adminlte-datatable id="table1" :heads="$heads" theme="danger">

    <h1 class="main-head">Product List</h1>

    <a class="btn btn-xl btn-default mx-1 shadow bg-success my-3" title="Create" href="{{ route('admin.products.create') }}"> Add Products</a>


            @foreach ($product as $products)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $products->name }}</td>
                <td><img src="{{ url("images/". $products->image) }}" style="height:60px;width:60px" alt="logo"></td>
                <td>{{ $products->slug }}</td>
                <td>

                    @foreach($products->categories as $cat)

                    {{$cat->name}},
                @endforeach</td>
                <td>Rs.{{ $products->price }}</td>
                <td>{{ $products->weight }}</td>




                <td class="d-flex" ><a  style="font-size:16px "class="btn btn-xs btn-default text-primary mx-1 shadow" title="Edit" href="{{ route('admin.products.edit', [$products->id]) }}"><i class="fa fa-lg fa-fw fa-pen"></i></a>
                    <form action="{{ route('admin.products.destroy', [$products->id]) }}" method="POST">
                        @csrf

                        @method('DELETE')

                        <button style="font-size:16px"  type="submit"  class="btn btn-xs btn-default text-danger mx-1 shadow" onclick="return confirm('Are you sure you want to delete this item?')" ><i class="fa fa-lg fa-fw fa-trash"></i></button>
                    </form>

            </tr>
        @endforeach
    </x-adminlte-datatable>


@endsection
@section('css')
    <link rel="stylesheet" href="{{ url('/css/style.css') }}">

@stop